import Link from 'next/link'

export const metadata = { title: 'Terms & Conditions | NETVYL' }

export default function TermsPage() {
  return <main style={{ minHeight: '100vh', padding: '32px 20px', background: '#0b1220', color: '#e5eef7' }}>
    <article className="card" style={{ maxWidth: 900, margin: '0 auto', padding: 32 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}><div><h1>NETVYL Terms &amp; Conditions</h1><p className="cell-sub">Last updated: 9 October 2026</p></div><Link href="/" className="btn">NETVYL home</Link></div>
      <div className="notice" style={{ margin: '20px 0' }}><strong>Review before publication:</strong> This is a working draft for NETVYL Business Solutions and NETVYL Digital Resources Global Ltd. Have a qualified lawyer review it for your business, pricing and applicable jurisdictions before relying on it as a contract.</div>
      <section><h2>1. About these terms</h2><p>These Terms &amp; Conditions govern access to and use of the NETVYL Business Management Platform, its web, desktop and mobile versions, and related support services (“NETVYL” or the “Service”). By creating an account, activating a license or using the Service, you agree to these terms on behalf of yourself and, where applicable, the organization you represent. If you do not agree, do not use the Service.</p></section>
      <section><h2>2. Accounts and authorized use</h2><p>You must provide accurate account information, protect your login credentials and promptly tell us if you suspect unauthorized access. The organization administrator is responsible for assigning suitable roles, managing staff access and ensuring that each user follows these terms. Do not share accounts, bypass access controls, interfere with the Service, or use it unlawfully.</p></section>
      <section><h2>3. License, subscription and payment</h2><p>Access is provided under the license or subscription selected for your organization. Applicable fees, billing periods, user limits and payment instructions will be presented during purchase or activation. Unless a separate written agreement says otherwise, a license is for the organization identified at activation and is subject to its status and expiry date. Submitting payment details does not itself confirm payment; access may depend on verification. Contact NETVYL for renewal or billing questions.</p></section>
      <section><h2>4. Your business data</h2><p>You retain your rights to the business records, customer information, files and other content that you or your users enter into NETVYL (“Customer Data”). You are responsible for having the rights and permissions needed to enter and use that data, for keeping it accurate, and for deciding which users may access it. You authorize NETVYL to host, process and use Customer Data as needed to provide, secure, maintain and support the Service. Do not upload unlawful, infringing or malicious content.</p><p>Use the in-product backup and export tools to keep copies of important records. You are responsible for storing exported backups securely and checking that your business can meet its own record-retention needs.</p></section>
      <section><h2>5. Privacy and security</h2><p>NETVYL processes account and operational data to provide the Service. Organizations using NETVYL are responsible for their own lawful handling of information about their customers and staff. A separate privacy notice should explain NETVYL’s specific data practices, retention, subprocessors and contact process; this document does not replace that notice. Contact <a href="mailto:netvylresources@gmail.com">netvylresources@gmail.com</a> with privacy questions or requests.</p></section>
      <section><h2>6. Availability and changes</h2><p>We work to keep NETVYL available and secure, but the Service may be interrupted for maintenance, upgrades, connectivity problems or events outside our reasonable control. Features may change as NETVYL is improved. We will use reasonable efforts to communicate material changes through the Service or our usual contact channels.</p></section>
      <section><h2>7. Intellectual property and feedback</h2><p>NETVYL and its software, design, documentation, branding and related materials are owned by NETVYL or its licensors and remain protected by applicable intellectual property rights. These terms grant you a limited, non-exclusive, non-transferable right to use the Service during your active license. If you provide suggestions, you allow NETVYL to use them to improve the Service without owing compensation.</p></section>
      <section><h2>8. Suspension and termination</h2><p>We may restrict or suspend access where a license expires, payment is not verified, an account presents a security risk, or use materially violates these terms or applicable law. Where reasonably possible, we will give notice and an opportunity to address the issue. You may stop using the Service and contact NETVYL about closing your account and handling your data. Data access and deletion timing should be confirmed with NETVYL before account closure.</p></section>
      <section><h2>9. Disclaimers and limits</h2><p>NETVYL provides tools to help manage business operations; it does not guarantee business outcomes, uninterrupted service, or that calculations and reports will be suitable for every business decision. You must review prices, quantities, taxes, stock, payments and reports before acting on them. To the extent permitted by applicable law, NETVYL is not responsible for indirect or consequential loss arising from use of the Service, data entry errors, connectivity failure or failure to maintain backups. Nothing in these terms excludes a liability that applicable law does not permit to be excluded.</p></section>
      <section><h2>10. Updates and contact</h2><p>We may update these terms. The current version will be posted on this page with its update date; continued use after an update takes effect indicates acceptance where permitted by law. For support or questions, email <a href="mailto:netvylresources@gmail.com">netvylresources@gmail.com</a>.</p></section>
      <p style={{ marginTop: 28 }}><Link href="/disclaimer">Read the NETVYL Disclaimer</Link></p>
    </article>
  </main>
}
