'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {supabaseBrowser} from '../../lib/supabase-browser'
import {PageHead,StatCard,Badge} from '../../components/ui'
import { CURRENT_APP_VERSION, DEFAULT_PLATFORM_APP_RELEASE, DEFAULT_PLATFORM_APP_SETTINGS, applyPlatformAppSettings, loadPlatformAppRelease, loadPlatformAppSettings, savePlatformAppRelease, savePlatformAppSettings, type PlatformAppRelease, type PlatformAppSettings } from '../../lib/platform-config'

async function isPlatformSuperAdmin(sb:any,userId:string|null|undefined){
 if(!sb||!userId) return false
 try{
   const {data,error}=await sb.rpc('netvyl_is_platform_super_admin')
   if(!error && data===true) return true
 }catch{}
 try{
   const {data,error}=await sb.from('organization_members').select('id').eq('user_id',userId).eq('active',true).ilike('role','super_admin').limit(1).maybeSingle()
   if(!error && !!data) return true
 }catch{}
 return false
}

export default function MasterAdmin(){
 const s=useMemo(()=>supabaseBrowser(),[]);const [orgs,setOrgs]=useState<any[]>([]),[licenses,setLicenses]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[devices,setDevices]=useState<any[]>([]),[account,setAccount]=useState<any>({}),[allowed,setAllowed]=useState<boolean|null>(null)
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''),[audit,setAudit]=useState<any[]>([]),[orgOpen,setOrgOpen]=useState(false),[licOpen,setLicOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[selectedOrg,setSelectedOrg]=useState(''),[adminInvite,setAdminInvite]=useState({org:'',email:'',name:''}),[inviteOpen,setInviteOpen]=useState(false),[settingsBusy,setSettingsBusy]=useState(false),[releaseBusy,setReleaseBusy]=useState(false),[platformSettings,setPlatformSettings]=useState<PlatformAppSettings>(DEFAULT_PLATFORM_APP_SETTINGS),[platformRelease,setPlatformRelease]=useState<PlatformAppRelease>(DEFAULT_PLATFORM_APP_RELEASE)
 const [orgForm,setOrgForm]=useState({name:'',slug:'',currency:'NGN'}),[licForm,setLicForm]=useState({plan:'professional',days:'365',max_users:'5',max_devices:'3',price:'0',buyer_email:''}),[accountForm,setAccountForm]=useState({bank_name:'',account_name:'NETVYL Digital Resources Global Ltd',account_number:'',transfer_instructions:'Use the payment reference shown with your license request.',payment_phone:'',payment_email:'',qr_code_url:''})
 const load=useCallback(async()=>{setError('');const [o,l,p,d,a,au]=await Promise.all([s.from('organizations').select('*').order('created_at',{ascending:false}),s.from('licenses').select('*').order('created_at',{ascending:false}),s.from('license_payment_requests').select('*').order('created_at',{ascending:false}),s.from('license_devices').select('*').order('last_seen_at',{ascending:false}),s.from('platform_payment_accounts').select('*').eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle(),s.from('audit_logs').select('id,organization_id,actor_user_id,action,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(100)]);if(o.error)setError(o.error.message);else setOrgs(o.data||[]);if(l.error)setError(x=>x?`${x} ${l.error.message}`:l.error.message);else setLicenses(l.data||[]);if(p.error)setError(x=>x?`${x} ${p.error.message}`:p.error.message);else setPayments(p.data||[]);setDevices(d.data||[]);setAudit(au.data||[]);setAccount(a.data||{});if(a.data)setAccountForm(a.data);},[s])
 useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){setAllowed(false);return}setAllowed(await isPlatformSuperAdmin(s,user.id))})()},[s]);useEffect(()=>{if(allowed)load()},[allowed,load])
 useEffect(()=>{let active=true;loadPlatformAppSettings(s).then((settings)=>{if(active){setPlatformSettings(settings);applyPlatformAppSettings(settings)}}).catch(()=>{});loadPlatformAppRelease(s).then((release)=>{if(active){setPlatformRelease(release)}}).catch(()=>{});return()=>{active=false}},[s])
 async function savePlatformConfig(){setSettingsBusy(true);setError('');try{const next=await savePlatformAppSettings(s,platformSettings);setPlatformSettings(next);setMsg('Global platform settings saved.');applyPlatformAppSettings(next)}catch(e:any){setError(e?.message||'Unable to save global settings.')}finally{setSettingsBusy(false)}}
 async function savePlatformRelease(){setReleaseBusy(true);setError('');try{const next=await savePlatformAppRelease(s,{...platformRelease,release_version:platformRelease.release_version || CURRENT_APP_VERSION});setPlatformRelease(next);setMsg('Shared app release updated.');}catch(e:any){setError(e?.message||'Unable to save app release.')}finally{setReleaseBusy(false)}}
 async function createOrg(){setBusy(true);setError('');const {data,error}=await s.rpc('master_create_organization',{p_name:orgForm.name,p_slug:orgForm.slug||orgForm.name,p_currency:orgForm.currency});if(error)setError(error.message);else{setMsg('Organization created.');setOrgOpen(false);setOrgForm({name:'',slug:'',currency:'NGN'});await load()}setBusy(false)}
 async function generateLicense(){setBusy(true);setError('');const {data,error}=await s.rpc('master_generate_license',{p_organization_id:selectedOrg,p_plan:licForm.plan,p_days:Number(licForm.days),p_max_users:Number(licForm.max_users),p_max_devices:Number(licForm.max_devices),p_price:Number(licForm.price),p_buyer_email:licForm.buyer_email||null});if(error)setError(error.message);else{setMsg(`License generated: ${data?.[0]?.license_key||''}. It is pending payment verification.`);setLicOpen(false);await load()}setBusy(false)}
 async function verifyPayment(id:string,approve:boolean){setBusy(true);setError('');const {error}=await s.rpc('master_verify_license_payment',{p_request_id:id,p_approve:approve,p_notes:approve?'Payment verified by Master Admin':'Payment rejected by Master Admin'});if(error)setError(error.message);else setMsg(approve?'Payment verified and license activated.':'Payment rejected.');await load();setBusy(false)}
 async function saveAccount(){setBusy(true);setError('');const payload={...accountForm,active:true};const {error}=account?.id?await s.from('platform_payment_accounts').update(payload).eq('id',account.id):await s.from('platform_payment_accounts').insert(payload);if(error)setError(error.message);else{setMsg('NETVYL payment account saved.');setAccountOpen(false);await load()}setBusy(false)}
 async function support(id:string){setBusy(true);setError('');const {error}=await s.rpc('master_start_support',{p_org_id:id});if(error)setError(error.message);else{localStorage.setItem('netvyl-support-organization',id);localStorage.setItem('netvyl-active-organization',id);window.location.href='/dashboard'}setBusy(false)}
 async function activateOrg(id:string){if(!window.confirm('Confirm that payment has been received and activate this organization?'))return;setBusy(true);setError('');try{const orgLicense=licenses.find(x=>x.organization_id===id && ['active','pending','expired','revoked'].includes(x.status));const orgRes=await s.rpc('master_set_organization_status',{p_org_id:id,p_status:'active'});if(orgRes.error)throw orgRes.error;const licenseRes=orgLicense?.id ? await s.rpc('master_set_license_status',{p_license_id:orgLicense.id,p_status:'active'}) : {error:null};if(licenseRes.error)throw licenseRes.error;setMsg('Organization activated after payment confirmation.');await load();}catch(e:any){setError(e?.message||'Unable to activate organization.')}finally{setBusy(false)}}
 async function setOrgStatus(id:string,status:string){if(!window.confirm(`${status==='suspended'?'Suspend':'Reactivate'} this organization?`))return;setBusy(true);const {error}=await s.rpc('master_set_organization_status',{p_org_id:id,p_status:status});setError(error?.message||'');if(!error)setMsg(`Organization ${status}.`);await load();setBusy(false)}
 async function deleteOrg(id:string,name:string){if(!window.confirm(`PERMANENTLY DELETE ${name}? This removes its organization data and cannot be undone.`))return;setBusy(true);const {error}=await s.rpc('master_delete_organization',{p_org_id:id});setError(error?.message||'');if(!error)setMsg(`${name} deleted.`);await load();setBusy(false)}
 async function inviteAdministrator(){setBusy(true);setError('');const {data,error}=await s.functions.invoke('invite-staff',{body:{organization_id:adminInvite.org,email:adminInvite.email,full_name:adminInvite.name,role:'administrator'}});if(error)setError(error.message);else if(data?.error)setError(data.error);else{setMsg('Company Administrator invitation sent.');setInviteOpen(false);setAdminInvite({org:'',email:'',name:''})}setBusy(false)}
 async function deactivateDevice(id:string){setBusy(true);const {error}=await s.rpc('master_deactivate_license_device',{p_device_id:id});if(error)setError(error.message);else setMsg('Device deactivated.');await load();setBusy(false)}
 async function sendLicenseEmail(id:string){
  if(!id){setError('License ID is missing. Refresh the page and try again.');return}
  setBusy(true);setError('');setMsg('')
  try{
    const {data:{session}}=await s.auth.getSession()
    if(!session?.access_token){setError('Your Master Admin session has expired. Please sign in again.');return}
    const {data,error}=await s.functions.invoke('send-license-email',{body:{licenseId:id}})
    if(error){
      let detail=error.message||'Failed to send a request to the Edge Function.'
      try{
        const ctx=(error as any).context
        if(ctx&&typeof ctx.json==='function'){
          const body=await ctx.json()
          detail=body?.error||body?.message||detail
        }
      }catch{}
      setError(`Email failed: ${detail}`)
      return
    }
    if(data?.error){setError(`Email failed: ${data.error}`);return}
    if(data?.success!==true){setError('Email failed: The Edge Function did not confirm delivery.');return}
    setMsg('License key emailed successfully.')
  }catch(e:any){setError(`Email failed: ${e?.message||String(e)}`)}
  finally{setBusy(false)}
}
 if(allowed===false)return <div className="card" style={{marginTop:20}}><h3>Access restricted</h3><p>You do not have permission to access Master Admin.</p></div>
 if(allowed!==true)return <div className="card" style={{marginTop:20}}>Checking access…</div>
 const active=licenses.filter(x=>x.status==='active').length,pending=licenses.filter(x=>x.payment_status==='pending'||x.status==='pending').length
 return <><PageHead title="Master Admin" subtitle="Platform control for organizations, licensing, payments, devices and support." actions={<><button className="btn" disabled={busy} onClick={load}>↻ Refresh</button><button className="btn" onClick={()=>setAccountOpen(true)}>Payment Account</button></>}/>{(error||msg)&&<div className={`notice ${error?'error':''}`} style={{marginTop:14}}>{error||msg}</div>}
 <div className="stats"><StatCard label="Organizations" value={orgs.length} icon="◆"/><StatCard label="Active licenses" value={active} icon="✓"/><StatCard label="Pending payment" value={pending} icon="₦"/><StatCard label="Registered devices" value={devices.filter(x=>x.active).length} icon="▣"/></div>
 <section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Global app configuration</h3><span>These settings are shared across all installed users and never touch company records.</span></div><button className="btn primary" disabled={settingsBusy} onClick={savePlatformConfig}>Save settings</button></div><div className="grid2"><label>App name<input value={platformSettings.app_name} onChange={e=>setPlatformSettings({...platformSettings,app_name:e.target.value})}/></label><label>Accent color<input type="color" value={platformSettings.accent_color} onChange={e=>setPlatformSettings({...platformSettings,accent_color:e.target.value})}/></label><label>App tagline<input value={platformSettings.app_tagline} onChange={e=>setPlatformSettings({...platformSettings,app_tagline:e.target.value})}/></label><label>Theme<select value={platformSettings.theme_mode} onChange={e=>setPlatformSettings({...platformSettings,theme_mode:e.target.value as 'dark'|'light'})}><option value="dark">Dark</option><option value="light">Light</option></select></label></div><label>Login banner<textarea value={platformSettings.login_banner} onChange={e=>setPlatformSettings({...platformSettings,login_banner:e.target.value})}/></label><div className="grid2" style={{marginTop:10}}><label><input type="checkbox" checked={platformSettings.enable_new_dashboard} onChange={()=>setPlatformSettings({...platformSettings,enable_new_dashboard:!platformSettings.enable_new_dashboard})}/> Enable new dashboard</label><label><input type="checkbox" checked={platformSettings.enable_dtf_calculator} onChange={()=>setPlatformSettings({...platformSettings,enable_dtf_calculator:!platformSettings.enable_dtf_calculator})}/> Enable DTF calculator</label><label><input type="checkbox" checked={platformSettings.enable_inventory_labels} onChange={()=>setPlatformSettings({...platformSettings,enable_inventory_labels:!platformSettings.enable_inventory_labels})}/> Enable inventory labels</label><label><input type="checkbox" checked={platformSettings.enable_global_branding} onChange={()=>setPlatformSettings({...platformSettings,enable_global_branding:!platformSettings.enable_global_branding})}/> Use global branding</label></div></section>
 <section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Shared app release</h3><span>Publish version updates and release notes to all installed users safely.</span></div><button className="btn primary" disabled={releaseBusy} onClick={savePlatformRelease}>Publish release</button></div><div className="grid2"><label>Current local build<input value={CURRENT_APP_VERSION} readOnly /></label><label>Release version<input value={platformRelease.release_version} onChange={e=>setPlatformRelease({...platformRelease,release_version:e.target.value})}/></label><label>Minimum supported version<input value={platformRelease.minimum_supported_version} onChange={e=>setPlatformRelease({...platformRelease,minimum_supported_version:e.target.value})}/></label><label><input type="checkbox" checked={platformRelease.is_force_update} onChange={()=>setPlatformRelease({...platformRelease,is_force_update:!platformRelease.is_force_update})}/> Force update required</label></div><label>Release notes<textarea value={platformRelease.release_notes} onChange={e=>setPlatformRelease({...platformRelease,release_notes:e.target.value})}/></label></section>
 <div className="dashboard-grid" style={{marginTop:16}}><section className="card"><div className="section-head"><div><h3>Organizations</h3><span>Each customer workspace is isolated from the platform and other organizations.</span></div><button className="btn primary" onClick={()=>setOrgOpen(true)}>＋ New organization</button></div><div className="tablewrap"><table><thead><tr><th>Organization</th><th>Status</th><th>License</th><th>Devices</th><th>Action</th></tr></thead><tbody>{orgs.map(o=>{const l=licenses.find(x=>x.organization_id===o.id&&x.status==='active')||licenses.find(x=>x.organization_id===o.id);const dc=devices.filter(x=>x.organization_id===o.id&&x.active).length;return <tr key={o.id}><td><strong>{o.name}</strong><small className="cell-sub">{o.slug}</small></td><td><Badge tone={o.status==='active'?'success':o.status==='suspended'?'danger':'warning'}>{String(o.status||'active').toUpperCase()}</Badge></td><td>{l?<><strong>{String(l.plan).toUpperCase()}</strong><small className="cell-sub">{l.status} · {l.expires_at?new Date(l.expires_at).toLocaleDateString('en-NG'):'No expiry'}</small></>:<span className="cell-sub">No license</span>}</td><td>{l?`${dc}/${l.max_devices||1}`:'—'}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn small" disabled={busy} onClick={()=>support(o.id)}>Manage / Support</button><button className="btn small" disabled={busy} onClick={()=>{setAdminInvite({org:o.id,email:'',name:''});setInviteOpen(true)}}>Invite Admin</button>{o.status==='active'?<button className="btn small" disabled={busy} onClick={()=>setOrgStatus(o.id,'suspended')}>Suspend</button>:o.status==='suspended'?<button className="btn small" disabled={busy} onClick={()=>setOrgStatus(o.id,'active')}>Reactivate</button>:<button className="btn small" disabled={busy} onClick={()=>activateOrg(o.id)}>Activate</button>}<button className="btn danger small" disabled={busy} onClick={()=>deleteOrg(o.id,o.name)}>Delete</button></div></td></tr>})}</tbody></table></div></section>
 <section className="card"><div className="section-head"><div><h3>License Management</h3><span>Payment must be verified before access is granted.</span></div><button className="btn" onClick={()=>setLicOpen(true)}>Generate license</button></div><div className="license-list">{licenses.map(l=><div className="license-row" key={l.id}><div><strong>{String(l.plan).toUpperCase()}</strong><small>{orgs.find(o=>o.id===l.organization_id)?.name||l.organization_id}</small><small>{l.license_key}</small><small>{l.buyer_email||'No buyer email'} · {l.max_devices||1} device(s)</small>{l.buyer_email&&<button className="btn small" disabled={busy} onClick={()=>sendLicenseEmail(l.id)}>Email key</button>}</div><Badge tone={l.status==='active'?'success':l.status==='pending'?'warning':'danger'}>{l.status}</Badge><span>{l.expires_at?new Date(l.expires_at).toLocaleDateString('en-NG'):'—'}</span></div>)}</div></section></div>
 <section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Payment Verification</h3><span>Review transfer evidence/reference before activating a license.</span></div></div><div className="tablewrap"><table><thead><tr><th>Company</th><th>Payer</th><th>Amount</th><th>Reference</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{orgs.find(o=>o.id===p.organization_id)?.name||p.organization_id}</td><td>{p.payer_name}<small className="cell-sub">{p.payer_email}</small></td><td>₦{Number(p.amount||0).toLocaleString('en-NG')}</td><td>{p.payment_reference||'—'}</td><td>{p.payment_date||'—'}</td><td><Badge tone={p.status==='verified'?'success':p.status==='rejected'?'danger':'warning'}>{p.status}</Badge></td><td>{p.status==='submitted'&&<><button className="btn small" disabled={busy} onClick={()=>verifyPayment(p.id,true)}>Verify</button> <button className="btn danger small" disabled={busy} onClick={()=>verifyPayment(p.id,false)}>Reject</button></>}</td></tr>)}{!payments.length&&<tr><td colSpan={7}>No payment submissions yet.</td></tr>}</tbody></table></div></section>
 <section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Device Activations</h3><span>Deactivate a device to free a license slot.</span></div></div><div className="tablewrap"><table><thead><tr><th>Company</th><th>Device</th><th>Platform</th><th>Last Seen</th><th>Status</th><th>Action</th></tr></thead><tbody>{devices.map(d=><tr key={d.id}><td>{orgs.find(o=>o.id===d.organization_id)?.name||d.organization_id}</td><td>{d.device_name}</td><td>{d.platform}</td><td>{d.last_seen_at?new Date(d.last_seen_at).toLocaleString('en-NG'):'—'}</td><td>{d.active?'ACTIVE':'INACTIVE'}</td><td>{d.active&&<button className="btn danger small" disabled={busy} onClick={()=>deactivateDevice(d.id)}>Deactivate</button>}</td></tr>)}</tbody></table></div></section><section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Platform audit log</h3><span>Recent administrative and support actions across organizations.</span></div></div><div className="tablewrap"><table><thead><tr><th>Time</th><th>Organization</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>{audit.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('en-NG')}</td><td>{orgs.find(o=>o.id===x.organization_id)?.name||x.organization_id||'Platform'}</td><td><strong>{x.action}</strong></td><td>{x.entity_type||'—'}</td><td><small>{JSON.stringify(x.details||{})}</small></td></tr>)}</tbody></table></div></section>
 {orgOpen&&<div className="modal-backdrop"><section className="modal card"><div className="section-head"><div><h3>New organization</h3><span>Create an isolated customer workspace.</span></div><button className="btn" onClick={()=>setOrgOpen(false)}>Close</button></div><label>Company name<input value={orgForm.name} onChange={e=>setOrgForm({...orgForm,name:e.target.value})}/></label><label>Slug<input value={orgForm.slug} onChange={e=>setOrgForm({...orgForm,slug:e.target.value})}/></label><label>Currency<input value={orgForm.currency} onChange={e=>setOrgForm({...orgForm,currency:e.target.value.toUpperCase()})}/></label><button className="btn primary wide" disabled={busy||!orgForm.name.trim()} onClick={createOrg}>Create organization</button></section></div>}
 {licOpen&&<div className="modal-backdrop"><section className="modal card"><div className="section-head"><div><h3>Generate pending license</h3><span>The buyer receives the key, pays, submits proof/reference, then you activate it.</span></div><button className="btn" onClick={()=>setLicOpen(false)}>Close</button></div><label>Organization<select value={selectedOrg} onChange={e=>setSelectedOrg(e.target.value)}><option value="">Select organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Buyer email<input type="email" value={licForm.buyer_email} onChange={e=>setLicForm({...licForm,buyer_email:e.target.value})}/></label><label>Plan<select value={licForm.plan} onChange={e=>setLicForm({...licForm,plan:e.target.value})}><option value="trial">Trial</option><option value="professional">Professional</option><option value="enterprise">Enterprise</option></select></label><div className="grid2"><label>Duration (days)<input type="number" min="1" value={licForm.days} onChange={e=>setLicForm({...licForm,days:e.target.value})}/></label><label>Price (NGN)<input type="number" min="0" value={licForm.price} onChange={e=>setLicForm({...licForm,price:e.target.value})}/></label><label>Max users<input type="number" min="1" value={licForm.max_users} onChange={e=>setLicForm({...licForm,max_users:e.target.value})}/></label><label>Max devices<input type="number" min="1" value={licForm.max_devices} onChange={e=>setLicForm({...licForm,max_devices:e.target.value})}/></label></div><button className="btn primary wide" disabled={busy||!selectedOrg} onClick={generateLicense}>Generate pending license</button></section></div>}
 {inviteOpen&&<div className="modal-backdrop"><section className="modal card"><div className="section-head"><div><h3>Invite Company Administrator</h3><span>The buyer's first administrator will receive a Supabase invitation.</span></div><button className="btn" onClick={()=>setInviteOpen(false)}>Close</button></div><label>Organization<select value={adminInvite.org} onChange={e=>setAdminInvite({...adminInvite,org:e.target.value})}><option value="">Select organization</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Administrator name<input value={adminInvite.name} onChange={e=>setAdminInvite({...adminInvite,name:e.target.value})}/></label><label>Administrator email<input type="email" value={adminInvite.email} onChange={e=>setAdminInvite({...adminInvite,email:e.target.value})}/></label><button className="btn primary wide" disabled={busy||!adminInvite.org||!adminInvite.email||!adminInvite.name} onClick={inviteAdministrator}>Send administrator invitation</button></section></div>}
 {accountOpen&&<div className="modal-backdrop"><section className="modal card"><div className="section-head"><div><h3>NETVYL payment account</h3><span>These details are shown to buyers during payment/renewal.</span></div><button className="btn" onClick={()=>setAccountOpen(false)}>Close</button></div><label>Bank name<input value={accountForm.bank_name} onChange={e=>setAccountForm({...accountForm,bank_name:e.target.value})}/></label><label>Account name<input value={accountForm.account_name} onChange={e=>setAccountForm({...accountForm,account_name:e.target.value})}/></label><label>Account number<input value={accountForm.account_number} onChange={e=>setAccountForm({...accountForm,account_number:e.target.value})}/></label><label>Transfer instructions<textarea value={accountForm.transfer_instructions} onChange={e=>setAccountForm({...accountForm,transfer_instructions:e.target.value})}/></label><div className="grid2"><label>Payment phone<input value={accountForm.payment_phone} onChange={e=>setAccountForm({...accountForm,payment_phone:e.target.value})}/></label><label>Payment email<input value={accountForm.payment_email} onChange={e=>setAccountForm({...accountForm,payment_email:e.target.value})}/></label></div><label>QR code image URL<input value={accountForm.qr_code_url} onChange={e=>setAccountForm({...accountForm,qr_code_url:e.target.value})}/></label><button className="btn primary wide" disabled={busy} onClick={saveAccount}>Save payment account</button></section></div>}
 </>
}
