'use client'
import {useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabaseBrowser} from '../../lib/supabase-browser'

function deviceId(){if(typeof window==='undefined')return '';const k='netvyl-device-id';let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v}

export default function Activate(){
 const s=useMemo(()=>supabaseBrowser(),[]);const router=useRouter();const [key,setKey]=useState(''),[email,setEmail]=useState(''),[name,setName]=useState(''),[platform,setPlatform]=useState('web'),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function activate(){setBusy(true);setError('');setMsg('');const {data,error}=await s.rpc('activate_netvyl_license',{p_license_key:key.trim(),p_buyer_email:email.trim(),p_device_id:deviceId(),p_device_name:name||`${platform.toUpperCase()} Device`,p_platform:platform,p_app_version:'1.0.0-v36'});if(error)setError(error.message);else if(!data?.[0]?.success)setError(data?.[0]?.message||'Activation failed');else{setMsg(`${data[0].message}. ${data[0].device_count}/${data[0].max_devices} device(s) active for this license.`);setTimeout(()=>router.push('/login'),1200)}setBusy(false)}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24}}><section className="card" style={{maxWidth:520,width:'100%'}}><div className="brand-block" style={{marginBottom:20}}><div className="brand-mark">N</div><div><div className="brand-name">NETVYL</div><div className="brand-sub">BUSINESS MANAGEMENT</div></div></div><h2>Activate NETVYL</h2><p className="cell-sub">Enter the license key sent to your registered email. Each license works only on the number of devices assigned by NETVYL.</p>{error&&<div className="notice error">{error}</div>}{msg&&<div className="notice">{msg}</div>}<label>License Key<input value={key} onChange={e=>setKey(e.target.value)} placeholder="NETVYL-XXXX-XXXX-XXXX" autoComplete="off"/></label><label>Buyer email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Device name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Office PC"/></label><label>Platform<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="web">Web</option><option value="windows">Windows</option><option value="android">Android</option><option value="ios">iOS</option></select></label><button className="btn primary wide" disabled={busy||!key.trim()||!email.trim()} onClick={activate}>{busy?'Activating…':'Activate License'}</button><div style={{marginTop:16,textAlign:'center'}}><a href="/login">Already activated? Sign in</a></div></section></main>
}
