'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabaseBrowser} from '../../lib/supabase-browser'
import {getActiveOrganizationId} from '../../lib/organization-context'
import {PageHead,Badge,Empty,Money} from '../../components/ui'


function printJob(job:any){
 const win=window.open('','_blank','width=900,height=700')
 if(!win)return
 const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
 win.document.write(`<!doctype html><html><head><title>${esc(job.job_no)} - Print Job</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#222}h1{margin:0 0 4px}.muted{color:#666}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:24px 0}.box{border:1px solid #ddd;border-radius:10px;padding:14px}.total{font-size:22px;font-weight:700}.header{display:flex;justify-content:space-between;border-bottom:2px solid #222;padding-bottom:16px}@media print{body{padding:10mm}.no-print{display:none}}</style></head><body><div class="header"><div><h1>${esc(job.job_no)}</h1><div class="muted">Production Job Ticket</div><div>Receipt: ${esc(job.receipt_no||'—')}</div></div><div><strong>${esc(job.job_date)}</strong><br>${esc(job.status)}</div></div><div class="grid"><div class="box"><strong>Customer</strong><br>${esc(job.customer_name_snapshot)}<br>${esc(job.customer_phone||'')}</div><div class="box"><strong>Material</strong><br>${esc(job.material_name_snapshot)}<br>Print &amp; Cut: ${job.print_cut?'Yes':'No'}</div><div class="box"><strong>Dimensions</strong><br>${esc(job.width)} × ${esc(job.height)} ${esc(job.unit)}<br>Quantity: ${esc(job.qty)}</div><div class="box"><strong>Production</strong><br>Billed area: ${esc(job.billed_sqft)} sqft<br>Material: ${esc(job.linear_length_ft)} ft</div></div><div class="box"><div>Production Total: ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(job.production_total||0))}</div><div>Print &amp; Cut: ${job.print_cut?'Yes':'No'}</div><div>Design: ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(job.design_charge||0))}</div><hr><div class="total">Grand Total: ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(job.grand_total||0))}</div><div>Paid: ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Number(job.amount_paid||0))}</div><div>Balance: ${new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(Math.max(0,Number(job.grand_total||0)-Number(job.amount_paid||0)))}</div></div><p class="muted">Powered by NETVYL Digital Resources Global Ltd</p><button class="no-print" onclick="window.print()">Print this job</button><script>window.onload=()=>window.print()</script></body></html>`)
 win.document.close()
}

export default function PrintStation(){const ORG=getActiveOrganizationId();
 const s=useMemo(()=>supabaseBrowser(),[]);const [rows,setRows]=useState<any[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState('')
 async function load(){const {data,error}=await s.from('print_queue').select('id,job_id,status,created_at,updated_at,jobs(id,job_no,receipt_no,job_date,customer_name_snapshot,material_name_snapshot,width,height,qty,unit,billed_sqft,linear_length_ft,production_total,design_charge,grand_total,amount_paid,print_cut,status)').eq('organization_id',ORG).order('created_at',{ascending:false});if(error)setMsg(error.message);setRows((data||[]).map((x:any)=>({...x,job:Array.isArray(x.jobs)?x.jobs[0]:x.jobs})).filter((x:any)=>x.job))}
 useEffect(()=>{load()},[])
 async function status(id:string,value:string){setBusy(id);const {error}=await s.from('print_queue').update({status:value,updated_at:new Date().toISOString()}).eq('id',id);setBusy('');setMsg(error?.message||`Queue updated to ${value}.`);load()}
 const stages=['pending','printing','finishing','completed']
 return <><PageHead title="Print Station" subtitle="Production queue — newest jobs appear first. Print only the selected job ticket." actions={<button className="btn" onClick={load}>↻ Refresh</button>}/><div className="production-board" style={{marginTop:20}}>{stages.map(stage=><section className="card kanban" key={stage}><div className="kanban-head"><h3>{stage}</h3><Badge tone={stage==='completed'?'success':'wine'}>{rows.filter(x=>String(x.status).toLowerCase()===stage).length}</Badge></div>{rows.filter(x=>String(x.status).toLowerCase()===stage).map(x=>{const j=x.job;return <div className="job-ticket" key={x.id}><strong>{j.job_no}</strong><small className="cell-sub">Receipt: {j.receipt_no||'—'}</small><span>{j.customer_name_snapshot||'Customer'}</span><small>{j.material_name_snapshot||''} · {j.job_date||''}</small><small>Total: <Money value={j.grand_total}/></small><div className="ticket-actions"><button className="btn small" onClick={()=>printJob(j)}>Print Job</button>{stage==='pending'&&<button className="btn small" disabled={busy===x.id} onClick={()=>status(x.id,'printing')}>Start</button>}{stage==='printing'&&<button className="btn small" disabled={busy===x.id} onClick={()=>status(x.id,'finishing')}>Finishing</button>}{stage==='finishing'&&<button className="btn primary small" disabled={busy===x.id} onClick={()=>status(x.id,'completed')}>Complete</button>}</div></div>})}{!rows.filter(x=>String(x.status).toLowerCase()===stage).length&&<div className="kanban-empty">No jobs</div>}</section>)}</div>{msg&&<div className="notice" style={{marginTop:16}}>{msg}</div>}</>}
