'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabaseBrowser} from '../../lib/supabase-browser'
import {getActiveOrganizationId} from '../../lib/organization-context'
import {PageHead,Money,Badge,Empty} from '../../components/ui'
import {downloadTextPdf,money} from '../../lib/pdf-report'

export default function Jobs(){
 const ORG=getActiveOrganizationId(); const s=useMemo(()=>supabaseBrowser(),[])
 const [newJob,setNewJob]=useState(''),[jobs,setJobs]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('ALL'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[myRole,setMyRole]=useState('')
 const [from,setFrom]=useState(''),[to,setTo]=useState('')
 async function load(){
  const uid=(await s.auth.getUser()).data.user?.id||''
  const {data:me}=await s.from('organization_members').select('role').eq('organization_id',ORG).eq('user_id',uid).maybeSingle(); setMyRole(String(me?.role||''));
  setLoading(true); const [{data,error},{data:orderData}]=await Promise.all([s.from('jobs').select('*').eq('organization_id',ORG).is('deleted_at',null),s.from('job_orders').select('id,order_no,customer_name_snapshot,status,grand_total,amount_paid,estimated_profit,actual_profit,created_at,due_at').eq('organization_id',ORG).order('created_at',{ascending:false}).limit(100)])
  setOrders(orderData||[]); if(error){setMsg(error.message);setJobs([])} else {const ordered=(data||[]).slice().sort((a,b)=>{const an=Number(String(a.job_no||'').replace(/\D/g,''))||0;const bn=Number(String(b.job_no||'').replace(/\D/g,''))||0;return bn!==an?bn-an:String(b.created_at||'').localeCompare(String(a.created_at||''))});setMsg('');setJobs(ordered)} setLoading(false)
 }
 useEffect(()=>{load();if(typeof window!=='undefined')setNewJob(new URLSearchParams(window.location.search).get('new')||'')},[])
 const shown=jobs.filter(j=>(status==='ALL'||j.status===status)&&(!from||j.job_date>=from)&&(!to||j.job_date<=to)&&`${j.job_no} ${j.customer_name_snapshot} ${j.receipt_no||''} ${j.material_name_snapshot||''}`.toLowerCase().includes(q.toLowerCase()))
 async function del(id:string,no:string){if(!window.confirm(`Delete ${no}? This will restore its inventory and remove its operational records.`))return;setBusy(id);const {error}=await s.rpc('delete_job_and_restore',{p_job_id:id});setBusy('');if(error)setMsg(error.message);else{setMsg(`${no} deleted and inventory restored.`);await load()}}

 async function delOrder(id:string,no:string){if(!window.confirm(`Delete ${no}? Inventory consumed by this order will be restored and its operational payment records removed.`))return;setBusy(id);const {error}=await s.rpc('delete_unified_order_v36_restore',{p_order_id:id});setBusy('');setMsg(error?error.message:`${no} deleted and inventory restored.`);if(!error)await load()}
 function exportHistory(){
  const title=`NETVYL Job History — ${from||'All dates'} to ${to||'All dates'}`
  const total=shown.reduce((n,j)=>n+Number(j.grand_total||0),0),paid=shown.reduce((n,j)=>n+Number(j.amount_paid||0),0)
  const lines=[`Organization: ${ORG||'Current workspace'}`,`Date range: ${from||'Beginning'} → ${to||'Today'}`,`Generated: ${new Date().toLocaleString('en-NG')}`,`Total jobs: ${shown.length}`,`Total billed: ${money(total)}`,`Total paid: ${money(paid)}`,`Total outstanding: ${money(Math.max(0,total-paid))}`,'','JOB HISTORY']
  shown.forEach(j=>lines.push(`${j.job_date||'—'} | ${j.job_no} | ${j.customer_name_snapshot||'—'} | ${j.material_name_snapshot||'—'} | Qty ${j.qty||0} | ${money(j.grand_total)} | Paid ${money(j.amount_paid)} | Bal ${money(Math.max(0,Number(j.grand_total||0)-Number(j.amount_paid||0)))}`))
  downloadTextPdf(`NETVYL-Job-History-${from||'all'}-${to||'all'}.pdf`,title,lines)
 }
 function printSelected(j:any){const w=window.open('','_blank','width=900,height=750');if(!w)return;const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const bal=Math.max(0,Number(j.grand_total||0)-Number(j.amount_paid||0));w.document.write(`<!doctype html><html><head><title>${esc(j.job_no)}</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#222}.head{display:flex;justify-content:space-between;border-bottom:2px solid #222;padding-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.box{border:1px solid #ddd;border-radius:8px;padding:12px}.total{font-size:20px;font-weight:700;margin-top:10px}@media print{body{padding:10mm}}</style></head><body><div class="head"><div><h1>${esc(j.job_no)}</h1><div>Production Job Ticket</div></div><div>${esc(j.job_date)}<br>${esc(j.status||'PENDING')}</div></div><div class="grid"><div class="box"><b>Customer</b><br>${esc(j.customer_name_snapshot)}</div><div class="box"><b>Receipt</b><br>${esc(j.receipt_no||'—')}</div><div class="box"><b>Material</b><br>${esc(j.material_name_snapshot||'—')}<br>Print & Cut: ${j.print_cut?'Yes':'No'}</div><div class="box"><b>Specification</b><br>${esc(j.width)} × ${esc(j.height)} ${esc(j.unit)}<br>Quantity: ${esc(j.qty)}</div><div class="box"><b>Production</b><br>Billed: ${esc(j.billed_sqft)} sqft<br>Material: ${esc(j.linear_length_ft)} ft</div><div class="box"><b>Payment</b><br>Total: ${money(j.grand_total)}<br>Paid: ${money(j.amount_paid)}<br>Balance: ${money(bal)}</div></div><p>Powered by NETVYL Digital Resources Global Ltd</p><script>window.onload=()=>window.print()</script></body></html>`);w.document.close()}
 return <><PageHead title="Job Records" subtitle="Search, inspect, print or export date-filtered job history." actions={<><button className="btn" onClick={load}>↻ Refresh</button><button className="btn primary" onClick={exportHistory} disabled={!shown.length}>Download Job History PDF</button><a className="btn" href="/new-job">＋ New Job</a></>}/>
 <section className="card" style={{marginTop:20}}><div className="toolbar"><input className="search-main" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search job number, customer, receipt or material…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{['pending','confirmed','queued','printing','finishing','completed','delivered','cancelled'].map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></div>
 <div className="grid2" style={{marginTop:12}}><label>From date<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To date<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
 {msg&&<div className="notice">{msg}</div>}<div className="notice" style={{marginTop:12}}>Showing <strong>{shown.length}</strong> job(s) in the selected range. PDF export follows the current search, status and date filters.</div>
 <div className="tablewrap"><table><thead><tr><th>Job</th><th>Date</th><th>Customer</th><th>Material</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={9}>Loading jobs…</td></tr>:shown.map(j=>{const bal=Math.max(0,Number(j.grand_total||0)-Number(j.amount_paid||0));return <tr key={j.id} style={j.job_no===newJob?{background:'rgba(128,23,61,.08)'}:undefined}><td><strong>{j.job_no}</strong><small className="cell-sub">{j.receipt_no||'Receipt pending'}</small></td><td>{j.job_date||'—'}</td><td>{j.customer_name_snapshot}</td><td>{j.material_name_snapshot||'—'}</td><td><Money value={j.grand_total}/></td><td><Money value={j.amount_paid}/></td><td className={bal>0?'wine-text':''}><Money value={bal}/></td><td><Badge tone={j.status==='completed'||j.status==='delivered'?'success':j.status==='cancelled'?'danger':'wine'}>{j.status||'PENDING'}</Badge></td><td><div style={{display:'flex',gap:6}}><button className="btn small" onClick={()=>printSelected(j)}>Print</button>{myRole==='administrator'&&<button className="btn danger small" disabled={busy===j.id} onClick={()=>del(j.id,j.job_no)}>{busy===j.id?'Deleting…':'Delete'}</button>}</div></td></tr>})}</tbody></table></div>{!loading&&!shown.length&&<Empty title="No jobs found" text="Adjust your filters or create a new job."/>}</section><section className="card" style={{marginTop:16}}><div className="section-head"><div><h3>Unified Orders</h3><span>DTF, Direct Image and Large Format orders created by the V36 engine.</span></div></div><div className="tablewrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Paid</th><th>Profit</th><th>Status</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.order_no}</strong></td><td>{o.customer_name_snapshot}</td><td><Money value={o.grand_total}/></td><td><Money value={o.amount_paid}/></td><td><Money value={o.actual_profit||o.estimated_profit}/></td><td><Badge tone={o.status==='completed'?'success':'wine'}>{o.status}</Badge></td><td>{myRole==='administrator'&&<button className="btn danger small" disabled={busy===o.id} onClick={()=>delOrder(o.id,o.order_no)}>{busy===o.id?'Deleting…':'Delete & restore'}</button>}</td></tr>)}</tbody></table></div>{!orders.length&&<div className="empty-state">No unified V36 orders yet.</div>}</section></>
}
